version: '3'
services:
  web:
    #image: secure_aggregation/server:thres171 #comment this if you dod not build you own docker image
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
    depends_on:
      - db
  
  db:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: federated
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    restart: unless-stopped